### ISSUE TITLE
Unable to compile the server

### ISSUE THREAD

**Issue by binishbala** [Netflix/dial-reference#10]
I am a newbie to cpp. When i am trying to evaluate the server, not able to understand how to set the target.  Also not able to find the path '/usr/local/i686-netflix-linux-gnu-4.3/bin/i686-netflix-linux-gnu- '. Any help will be appreciated.

Thanks
Binish

**Comment by xuwen0306** [comment]
If you have android compile environment, it's easy to create a Android.mk to make the whole project.  If you need to setup your owner cross compile environment, it may need a bit time.

**Comment by hustweimin** [comment]
After I compile the server, copy the dialserver to my target platform (stb), execute it, but it report "Permission denied ". So I checked the permission and got following result:
ls -l dialserver
-rwxr-xr-x    1 root     0           103728 Apr 14 10:26 dialserver

I logon to the bos as root, so I think I have the permission.
Any help will be appreciated.

Thanks
Catherine

**Comment by chintan09** [comment]
Fixed the linux build errors for the server side with the commit  50f7a5085d65f1222c913394149478ad4f981fe3, closing this issue. 

@hustweimin  - Have you cross compiled for the right platform?
