### ISSUE TITLE
How to register an app in DIAL registry?

### ISSUE THREAD

**Issue by strobil** [Netflix/dial-reference#27]
Hello!
Any idea how i can add an app to DIAL registry?
Website http://www.dial-multiscreen.org/ is not working...

**Comment by strobil** [comment]
@kemorrisnf please help

**Comment by vietkute02** [comment]
same error, this page response 404 a week ago

**Comment by kemorrisnf** [comment]
@strobil, we are working on it.  We'll ping this thread when it is back up.

**Comment by kemorrisnf** [comment]
@strobil, @vietkute02 we are still sorting out the domain name issue.  You can access the site from [this url](https://sites.google.com/a/dial-multiscreen.org/dial/) in the interim.

**Comment by strobil** [comment]
> @strobil, @vietkute02 we are still sorting out the domain name issue. You can access the site from [this url](https://sites.google.com/a/dial-multiscreen.org/dial/) in the interim.

Thank you bro!
