### ISSUE TITLE
Dial data memory

### ISSUE THREAD

**Issue by SylHappy** [Netflix/dial-reference#4]
static void handle_dial_data(struct mg_connection *conn,
const struct mg_request_info *request_info,
const char *app_name,
const char *origin_header,
int use_payload) {
...
app->dial_data = parse_params(body);
...
It seems dial_data not free if each time a DIAL server receives a POST request sent to an additionalDataUrl.

Could you help confirm it?

Thanks.

**Comment by chintan09** [comment]
Thanks for pointing this out, fixed in eb89f3cbd3a3b08e536b1fafda548520264895d1
