### ISSUE TITLE
ds_unlock(ds) is called twice

### ISSUE THREAD

**Issue by liubangbo** [Netflix/dial-reference#5]
int DIAL_register_app(DIALServer _ds, const char *app_name,
                      struct DIALAppCallbacks *callbacks, void *user_data,
                      int useAdditionalData,
                      const char_ corsAllowedOrigin) {
    DIALApp **ptr, *app;
    int ret;

```
ds_lock(ds);
ptr = find_app(ds, app_name);
if (*ptr != NULL) {  // app already registered
    # ds_unlock(ds);
    ret = 0;
} else {
    app = malloc(sizeof(DIALApp));
    app->callbacks = *callbacks;
    app->name = strdup(app_name);
    app->next = *ptr;
    app->state = kDIALStatusStopped;
    app->callback_data = user_data;
    app->dial_data = retrieve_dial_data(app->name);
    app->useAdditionalData = useAdditionalData;
    app->corsAllowedOrigin[0] = '\0';
    if (corsAllowedOrigin &&
        strlen(corsAllowedOrigin) < sizeof(app->corsAllowedOrigin)) {
      strcpy(app->corsAllowedOrigin, corsAllowedOrigin);
    }
    *ptr = app;
    ret = 1;
}
```

   #  ds_unlock(ds);
    return ret;
}

I think ds_unlock(ds) is called twice .   Can you help to confirm it ? 
Many thanks.

**Comment by maxvonhippel** [comment]
Yes, this is definitely calling twice.  Created pull request.

**Comment by chintan09** [comment]
PR is merged already, closing.
